[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
libsql = "0.3.1"
tokio = { version = "1", features = ["full"] }
warp = "0.3.5"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
